package.json
Fix the broken Travis CI build because of zone.js https://github.com/angular/zone.js/issues/240
=> chore(package): Add explicit dependency on tsd

.npmrc, package.json
Added .npmrc with save-exact = true. New releases of third party libraries will be picked up by
Greenkeeper, which will create PRs with those upgrades. Travis CI will build and test those PRs so
we can upgrade without surprises.
=> chore(package): Depend on specific versions of libraries

.gitignore, .npmignore, README.md, examples/package.json, examples/typings.json, package.json, src/vg-player/vg-player.spec.ts, src/vg-player/vg-player.ts, typings.json
Updated to Angular2-beta.6 and switched to typings instead of tsd
=> chore(Libraries): ng2-beta.6 and typings

src/events/vg-events.ts, src/services/vg-api.spec.ts, src/services/vg-api.ts
Moved from listeners to observables on all media events. Added all available media events to
VgEvents. #close 32
32
=> refactor(API): Switch to Observables

src/vg-controls/vg-controls.spec.ts, src/vg-controls/vg-controls.ts, src/vg-player/vg-player.ts
Updated autohide to work through the API instead of being coupled with VgPlayer.
#close #28
=> refactor(autohide): Refactor autohide

CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Added contribution guidelines and templates.
=> docs(Contrib): Contributing guidelines

package.json
Please explain the changes you made here.
http://greenkeeper.io/
=> chore(package): update karma-chrome-launcher to version 0.2.3

karma-test-shim.js, karma.conf.js, package.json, src/services/vg-api.spec.ts, src/services/vg-fullscreen-api.spec.ts, src/services/vg-utils.spec.ts, src/vg-controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.spec.ts, src/vg-controls/vg-time-display/vg-time-display.spec.ts, src/vg-cue-points/vg-cue-points.spec.ts, src/vg-media/i-playable.ts, src/vg-media/vg-media.spec.ts, src/vg-media/vg-media.ts, src/vg-player/vg-player.spec.ts
Added tests for everything except vg-360
=> test(tests): Missing tests

package.json
=> feat(RC2): Updated to RC2

controls.ts, examples/single-media-player/src/single-media-player.html, src/vg-controls/vg-volume/vg-volume.d.ts, src/vg-controls/vg-volume/vg-volume.spec.ts, src/vg-controls/vg-volume/vg-volume.ts
Please explain the changes you made here.
- Created tests, if possible
- All tests passing
- Extended the README / documentation, if necessary
Added new volume bar control and corresponding tests. The component can be seen in the "Single Media
Player" demo.
=> feat(vg-controls): Added VgVolume control

fonts/videogular.css, src/vg-player/vg-player.ts
=> fix(vg-player): Fix video size

.npmignore, package.json
=> fix(build): Fix NPM build

src/services/vg-api.ts, src/services/vg-fullscreen-api.ts, src/vg-buffering/vg-buffering.ts, src/vg-controls/vg-abstract-control.ts, src/vg-controls/vg-controls.ts, src/vg-controls/vg-scrub-bar/vg-scrub-bar.ts, src/vg-cue-points/vg-cue-points.ts, src/vg-media/vg-media.ts, src/vg-player/vg-player.ts
=> fix(types): Fix implicit any types

src/vg-controls/vg-fullscreen/vg-fullscreen.ts
Fix fullscreen button binding by using event instead of a bind to the static property
=> fix(fullscreen): Fix fullscreen button

src/vg-buffering/vg-buffering.spec.ts
Please explain the changes you made here.
- Created tests, if possible
- All tests passing
- Extended the README / documentation, if necessary
=> Fix description in Buffering spec

package.json
Add parallelshell to scripts
close #268
=> build(build): Fix parallelshell on windows

src/events/vg-events.ts, src/vg-media/i-playable.ts, src/vg-media/vg-media.ts
Add all native events to the API and update IPlayable.
=> feat(API): Improve API events

src/vg-controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time.ts
=> fix(controls): Fix NaN on VgScrubBarBufferingTime

package.json, typings.json, typings/globals/es6-shim/typings.json, typings/globals/jasmine/typings.json
Remove typings and add @types/jasmine
=> fix(types): Remove typings

README.md
It's non trivial that the developer must open the docs folder to find out the installation instructions. A quick link to the getting started would come in very handy.
=> docs(readme): update readme.md

docs/how-it-works.md
Please explain the changes you made here.
Fixed link to Using the API
=> docs: update how-it-works.md

src/controls/controls.ts, src/controls/vg-time-display/vg-time-display.ts
Add custom pipe to support hours in different timezones
=> fix(controls): Support hours

package.json
Update dependencies to versions suggested by greenkeeper
=> chore(package): Update libs

LICENSE, karma.conf.js, package.json, src/controls/vg-playback-button/vg-playback-button.ts, tsconfig.json
Migrate to core-js to fix problems with triple-slash directives added by es6-shim
close #317
=> chore(package): Migrate to core-js

src/buffering/vg-buffering.ts, src/controls/vg-controls.ts, src/controls/vg-fullscreen/vg-fullscreen.spec.ts, src/controls/vg-fullscreen/vg-fullscreen.ts, src/controls/vg-mute/vg-mute.ts, src/controls/vg-play-pause/vg-play-pause.ts, src/controls/vg-playback-button/vg-playback-button.ts, src/controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts, src/controls/vg-time-display/vg-time-display.ts, src/controls/vg-track-selector/vg-track-selector.ts, src/controls/vg-volume/vg-volume.ts, src/core/services/vg-api.ts, src/core/services/vg-fullscreen-api.spec.ts, src/core/services/vg-fullscreen-api.ts, src/core/vg-player/vg-player.spec.ts, src/core/vg-player/vg-player.ts, src/ima-ads/vg-ima-ads.ts, src/overlay-play/vg-overlay-play.ts, src/streaming/vg-dash/vg-dash.ts, src/streaming/vg-hls/vg-hls.ts
**BREAKING CHANGE:**
Now VgFullscreenAPI is not anymore static and you need to grab it from VgAPI. E.g: When you grab the API on the onPlayerReady($event) EventEmitter, then inside that callback you can grab the VgFullscreenAPI from VgAPI like
```
onPlayerReady(api: VgAPI) {
this.api = api;
this.fsAPI = this.api.fsAPI;
}
```
close #350
=> Feat/add is player ready and fix fullscreen (BREAKING CHANGE)

package.json, src/controls/vg-controls.ts
Add vgFor input property to VgControls instead of using attribute
=> fix(controls): Add vgFor input property to VgControls

src/controls/vg-track-selector/vg-track-selector.ts, src/controls/vg-volume/vg-volume.spec.ts, src/controls/vg-volume/vg-volume.ts
Fix volume and track selector in Firefox and Safari
related with https://github.com/videogular/videogular2/pull/423
=> fix(controls): Fix volume and track selector in Firefox and Safari

src/core/services/vg-fullscreen-api.ts, src/ima-ads/vg-ima-ads.ts
Fix fullscreen cross-browser (iOS & Firefox)
relates https://github.com/videogular/videogular2/issues/287
=> fix(fullscreen): Fix fullscreen cross-browser

src/controls/vg-playback-button/vg-playback-button.ts
Allow customisation through attributes
If this (simple) change is desired I will write some tests and validation.
=> Configurable playback speed values

docs/how-it-works.md, src/controls/vg-scrub-bar/vg-scrub-bar.spec.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts
=> fix(controls): Set vgSlider as default

src/core/services/vg-api.spec.ts, src/core/services/vg-api.ts, src/core/vg-media/vg-media.ts
Add unregister media method to dynamically remove medias from api
=> feat(api): Add unregister media method to api

docs/SUMMARY.md, docs/getting-started/README.md, docs/getting-started/how-videogular-works.md, docs/getting-started/using-the-api.md, docs/modules/core/README.md, docs/modules/core/services/vg-api/README.md, docs/modules/core/vg-cue-points/README.md, docs/modules/core/vg-media/README.md, docs/modules/core/vg-player/README.md
Add docs for VgMedia and update other documentation in general
=> docs(docs): Add docs for VgMedia

docs/SUMMARY.md, docs/modules/buffering/README.md, docs/modules/buffering/vg-buffering/README.md, docs/modules/controls/README.md, docs/modules/controls/vg-controls/README.md, docs/modules/core/events/README.md, docs/modules/core/services/vg-fullscreen-api/README.md, docs/modules/core/services/vg-utils/README.md, docs/modules/core/states/README.md, docs/modules/overlay-play/README.md, docs/modules/overlay-play/vg-overlay-play/README.md
Completed docs for core, buffering and overlay-play modules. Started docs for controls module.
=> docs(docs): Add docs for core, buffering, overlay-play and controls module

src/buffering/buffering.ts, src/buffering/vg-buffering.ts, src/controls/vg-controls.ts, src/controls/vg-fullscreen/vg-fullscreen.ts, src/controls/vg-mute/vg-mute.ts, src/controls/vg-play-pause/vg-play-pause.ts, src/controls/vg-playback-button/vg-playback-button.ts, src/controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts, src/controls/vg-time-display/vg-time-display.ts, src/controls/vg-track-selector/vg-track-selector.ts, src/controls/vg-volume/vg-volume.ts, src/core/services/vg-controls-hidden.ts, src/core/vg-cue-points/vg-cue-points.ts, src/core/vg-player/vg-player.ts, src/ima-ads/vg-ima-ads.ts, src/overlay-play/vg-overlay-play.ts, src/streaming/vg-dash/vg-dash.ts, src/streaming/vg-hls/vg-hls.ts
Unsubscribe from all observables in all modules
=> fix(performance): Unsubscribe from all observables

package.json, src/core/services/vg-fullscreen-api.spec.ts, src/core/vg-cue-points/vg-cue-points.spec.ts
Update rxjs to v5.1.0
relates #493
=> fix(dependencies): Update rxjs to v5.1.0

docs/modules/ima-ads/README.md, docs/modules/ima-ads/vg-ima-ads/README.md, src/core/vg-media/vg-media.ts
Add docs for videogular/ima-ads module
=> docs(docs): Add docs for videogular/ima-ads module

src/ima-ads/vg-ima-ads.ts
Set skip button as optional, it is no long required
=> fix(ima-ads): Set skip button as optional

docs/modules/streaming/README.md, docs/modules/streaming/vg-dash/README.md, docs/modules/streaming/vg-hls/README.md
Add docs for VgStreaming module
=> docs(streaming): Add docs for VgStreaming module

src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts
Transform TextTrackCueList to Array to make it work on IE11/Edge.
Fixed also some UI problems with VgScrubBar component.
close #369
=> fix(controls): Fix VgScrubBarCuePoints for IE11/Edge

docs/modules/core/services/vg-api/README.md, docs/modules/core/vg-media/README.md, src/core/services/vg-api.ts, src/core/vg-media/i-playable.ts, src/core/vg-media/vg-media.ts
Add track and cue dynamically, create a function for manager cueDynamic in the API, update the documentation, modify IPlayable for support track function.
add track for addCue function
change tracker for optional
Add addTextTrack to documentation
Thank you!
=> Feat(core): Add create track and cues dynamically

docs/modules/core/services/vg-api/README.md, docs/modules/core/vg-media/README.md, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.spec.ts, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/core/services/vg-api.ts, src/core/vg-cue-points/vg-cue-points.spec.ts, src/core/vg-cue-points/vg-cue-points.ts, src/core/vg-media/i-playable.ts, src/core/vg-media/vg-media.ts
Fix addTextTrack to create tracks not cues
=> fix(core): Fix addTextTrack to create tracks not cues

package.json, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.spec.ts, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/core/vg-cue-points/vg-cue-points.spec.ts, src/core/vg-cue-points/vg-cue-points.ts
Fix compilation problem with IterableDiffer Generic
=> fix(core): Fix compilation problem with IterableDiffer Generic

package.json
Fix compilation error VgCoreModule is not an NGModule
=> fix(core): Fix compilation error

src/controls/vg-controls.ts, src/core/core.ts, src/core/vg-player/vg-player.spec.ts, src/core/vg-player/vg-player.ts, src/overlay-play/vg-overlay-play.spec.ts, src/overlay-play/vg-overlay-play.ts
Hide cursor when controls are hidden and native fullscreen mode is set
close #526
=> feat(core): Hide cursor when controls are hidden in native fullscreen

docs/SUMMARY.md, docs/modules/core/services/vg-controls-hidden/README.md
Add docs for VgControlsHidden service
=> docs(core): Add docs for VgControlsHidden service

src/controls/vg-scrub-bar/vg-scrub-bar.spec.ts, src/core/vg-media/vg-media.spec.ts, src/core/vg-media/vg-media.ts
Bug fix. Enables the player to operate properly when ChangeDetection is set to OnPush. Without this fix it doesn't update the UI as the video plays.
(See #525)
Y - I've read the (contributing)[https://github.com/videogular/videogular2/blob/master/CONTRIBUTING.md] guidelines
Y - Code compiles correctly (run `npm start`)
Y - Created tests (if necessary) [updated tests to inject change detector ref]
Y - All tests passing (run `npm test`)
N/A - Extended the README / documentation (if necessary)
=> Fix change detection, support OnPush (fixes #525)

package.json
Support OnPush change detection strategy and return new track from addTextTrack
Added also commit message validation and updated to husky in deprecation of ghooks
=> fix(core): Support OnPush strategy and return track on addTextTrack

src/core/vg-media/vg-media.ts
Fix load of HLS streams
close #539
=> fix(streaming): Fix load of HLS streams

src/core/vg-media/vg-media.spec.ts, src/core/vg-media/vg-media.ts
Prevent duplicate loads for DASH and HLS sources
=> fix(core): Avoid load media when it's a blob

src/buffering/vg-buffering.spec.ts, src/buffering/vg-buffering.ts, src/core/vg-media/i-playable.ts, src/core/vg-media/vg-media.ts, src/overlay-play/vg-overlay-play.spec.ts, src/overlay-play/vg-overlay-play.ts
This fix avoid to see at the same time buffering icon and playing icon.
=> Fix buffering interoperability between plugins

src/core/vg-media/vg-media.ts
Detect when sources or src attribute has been changed
close #547
=> fix(core): Detect when sources or src attribute has been changed

src/core/vg-media/vg-media.ts
Fix play request interrupted error by handling Promise returned by play() method
close #431
=> fix(core): Fix play request interrupted error

src/core/vg-media/vg-media.ts
Fix play after video ended
close #568
=> fix(core): Fix play after video ended

docs/modules/streaming/vg-dash/README.md, src/streaming/streaming.ts, src/streaming/vg-dash/vg-dash.ts
Add DRM support.
To use it you must add the new input properties `vgDRMLicenseServer` and `vgDRMToken` (if you need a token to play the media).
For example, for this template:
```html
<vg-player (onPlayerReady)="onPlayerReady($event)">
<vg-overlay-play></vg-overlay-play>
<vg-buffering></vg-buffering>
<vg-controls>
<vg-play-pause></vg-play-pause>
<vg-scrub-bar>
<vg-scrub-bar-current-time></vg-scrub-bar-current-time>
<vg-scrub-bar-buffering-time></vg-scrub-bar-buffering-time>
</vg-scrub-bar>
<vg-time-display vgProperty="left" vgFormat="mm:ss"></vg-time-display>
<vg-mute></vg-mute>
<vg-volume></vg-volume>
<vg-fullscreen></vg-fullscreen>
</vg-controls>
<video #media
[vgMedia]="media"
[vgDash]="currentStream.source"
[vgDRMToken]="currentStream.token" …
```
=> feat(streaming): Add DRM support

src/controls/vg-track-selector/vg-track-selector.ts
Set ARIA value in VgTrackSelector
Fix AOT
Close issue #623
=> fix(controls): Set ARIA value in VgTrackSelector

src/controls/vg-scrub-bar/vg-scrub-bar.ts
Vertical alignment for scrub bar
=> fix(controls): Vertical alignment for scrub bar

src/controls/vg-scrub-bar/vg-scrub-bar.ts
=> fix(controls): Remove console.log()

package.json
Set dependencies as peerDependencies
=> fix(dependencies): Set dependencies as peerDependencies

docs/getting-started/using-the-api.md, docs/modules/core/vg-media/README.md
=> docs(docs): Fix typos

src/controls/vg-mute/vg-mute.ts
Fix mute button when initial volume is 0
#643
=> fix(controls): Fix mute button when initial volume is 0

src/controls/vg-scrub-bar/vg-scrub-bar.spec.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts
Fix seek to not stop seeking when leaving out the scrub bar
=> fix(controls): Fix seek to not stop seeking when leaving out the scrubbar

src/controls/vg-scrub-bar/vg-scrub-bar.ts
Protect from errors on mouse events
#692
=> fix(controls): Protect from errors on mouse events

README.md
=> fix getting started link

src/controls/vg-track-selector/vg-track-selector.ts
Fix for windows only, now the tracks names are invisible anymore
#691
=> fix(controls): Fix track options visibility

src/controls/controls.ts, src/controls/vg-quality-selector/vg-quality-selector.spec.ts, src/controls/vg-quality-selector/vg-quality-selector.ts, src/core/core.ts, src/streaming/vg-dash/vg-dash.ts
Add quality switcher, Hls.js and Dash.js switcher
#632
=> feat(controls): Add quality switcher

docs/SUMMARY.md, docs/modules/controls/vg-quality-selector/README.md, docs/modules/core/bitrate-option/README.md, docs/modules/streaming/vg-dash/README.md, docs/modules/streaming/vg-hls/README.md, src/controls/vg-quality-selector/vg-quality-selector.ts, src/streaming/vg-dash/vg-dash.ts, src/streaming/vg-hls/vg-hls.ts
=> docs(controls): Add quality switcher docs

karma-test-shim.js, package.json, src/buffering/vg-buffering.ts, src/controls/vg-controls.spec.ts, src/controls/vg-controls.ts, src/controls/vg-fullscreen/vg-fullscreen.ts, src/controls/vg-mute/vg-mute.ts, src/controls/vg-play-pause/vg-play-pause.ts, src/controls/vg-playback-button/vg-playback-button.ts, src/controls/vg-quality-selector/vg-quality-selector.ts, src/controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar-cue-points/vg-scrub-bar-cue-points.ts, src/controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time.ts, src/controls/vg-scrub-bar/vg-scrub-bar.ts, src/controls/vg-time-display/vg-time-display.ts, src/controls/vg-track-selector/vg-track-selector.ts, src/controls/vg-volume/vg-volume.ts, src/core/services/vg-controls-hidden.spec.ts, src/core/services/vg-controls-hidden.ts, src/core/services/vg-fullscreen-api.ts, src/core/vg-cue-points/vg-cue-points.spec.ts, src/core/vg-cue-points/vg-cue-points.ts, src/core/vg-media/i-playable.ts, src/core/vg-media/vg-media.ts, src/core/vg-player/vg-player.ts, src/ima-ads/vg-ima-ads.ts, src/overlay-play/vg-overlay-play.ts, src/streaming/vg-dash/vg-dash.ts, src/streaming/vg-hls/vg-hls.ts
Migration to Angular 6 and RxJS 6
=> Angular 6 Migration

src/ima-ads/vg-ima-ads.ts
Please explain the changes you made here. Commit your changes with `npm run commit` instead of `git commit`.
Specify if it's a fix, feature or breaking change to update the version on NPM.
Thank you!
- Created tests (if necessary)
- All tests passing (run `npm test`)
- Extended the README / documentation (if necessary)
=> Feat: add event for play/pause/skip IMA-ADS

src/core/vg-cue-points/vg-cue-points.ts
Fix cue points with native controls
=> fix(core): Fix cue points with native controls

.gitignore, .travis.yml, package-lock.json, package.json
=> fix(travis): Fix semantic-release on travis

.travis.yml
=> fix(travis): Remove travis cache
