package.json

Commitizen is deprecating czConfig in favor of npm's config object
https://github.com/commitizen/cz-cli/issues/30

chore(package): Move czConfig into config.commitizen

---

src/streaming/vg-hls/vg-hls.ts

Add support for preload attribute. Add `preload="none"` to the `video` tag if you don't want to preload HLS media data.
close #333

feat(hls): Add support for preload tag

---

src/controls/vg-controls.spec.ts
src/controls/vg-controls.ts
src/core/vg-cue-points/vg-cue-points.spec.ts
src/core/vg-cue-points/vg-cue-points.ts
src/core/vg-media/vg-media.ts

Importing directly from the rxjs class modules, e.g. `'rxjs/Observable'`, and then patching imports
for only the used operator modules, e.g. `'rxjs/add/observable/fromEvent'`, avoids using the omnibus `'rxjs/Rx'` module and makes it easier for consumers to tree-shake their bundles correctly with tools like rollup & webpack. More information is avaiable in the [rxjs readme](https://github.com/ReactiveX/rxjs#installation-and-usage) as well as in [rxjs#1888](https://github.com/ReactiveX/rxjs/issues/1888).
* Changed the `import` statements that pointed to `'rxjs'` (src/core/vg-media/vg-media.d.ts) and `'rxjs/Rx'` (in src/core/vg-cue-points/vg-cue-points.ts, src/core/vg-cue-points/vg-cue-points.spec.ts) to import directly from `'rxjs/Subscription'`/`'rxjs/Observer'` and `'rxjs/Observable'` …

refactor(rxjs): Import operators individually from rxjs for tree-shaking

---

src/core/vg-media/i-playable.ts

IMediaSubscriptions was missing startAds and endAds observables. You can
catch those events with:
`this.api.getDefaultMedia().subscriptions.endAds.subscribe()`
`this.api.getDefaultMedia().subscriptions.startAds.subscribe()`
In reference to https://github.com/videogular/videogular2/issues/358
Seems there aren't any tests for ima-ads so I couldn't check. Changes do work in my project.

Adds missing observables for start and end of ads.

---

src/controls/vg-volume/vg-volume.spec.ts
src/controls/vg-volume/vg-volume.ts

Use bounding box of the volume bar to get the correct left position to calculate the volume. Also switched to ViewChild. Fixes #286.
Before:
After:

fix(controls): make volume control rely on bounding box

---

src/controls/controls.ts
src/controls/vg-controls.spec.ts
src/controls/vg-controls.ts
src/controls/vg-scrub-bar/vg-scrub-bar.spec.ts
src/controls/vg-scrub-bar/vg-scrub-bar.ts
src/core/services/vg-controls-hidden.spec.ts
src/core/services/vg-controls-hidden.ts

When vg-scrub-bar was placed outside of vg-controls component it would not hide
closes #337

fix(vg-scrub-bar): Hide scrub bar along with controls

---

docs/getting-started.md
docs/how-it-works.md
docs/master-media.md
docs/using-the-api.md
docs/vg-cue-points/vg-cue-points.md
docs/vg-player/vg-player.md
src/controls/vg-controls.ts
src/core/vg-media/vg-media.spec.ts
src/core/vg-media/vg-media.ts

Now we can create our custom media elements, so this allows us to play anything that has a begin and an end.
BREAKING CHANGE: Now `vgMedia` expects a view reference as param. Created a new property for `vgMaster`.
Before: `<video vgMedia="master">`
After: `<video #myMedia [vgMedia]="myMedia" [vgMaster]="true">`

feat(vgMedia): Now we can create our custom media elements

---

src/controls/vg-volume/vg-volume.spec.ts
src/controls/vg-volume/vg-volume.ts

On iphone 5 (320px) screen, width of vg-volume component is 67px. Older calculation assumes its 100px and doesn't work correctly. (mousePosX - volumeBarOffsetLeft) / volumeBarWidth * 100 on calculateVolume function fixes the problem.

fix volume percent calculation on small screen

---

docs/how-it-works.md
src/controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time.ts
src/controls/vg-scrub-bar/vg-scrub-bar.spec.ts
src/controls/vg-scrub-bar/vg-scrub-bar.ts

Users tend to use move gestures to seek through the video, mostly in mobile devices. This commit
enables mouse and touch events to allow this type of seeks. A new option to show a circle in
VgScrubBarCurrentTime is also available. 
- Modified `vg-scrub-bar` to allow slide movements to seek through the video. This can be enabled using the `[vgSlider]="true"` attribute.
- Modified `vg-scrub-bar-current-time` to show a circle in the current time position. This can be enabled also using the `[vgSlider]="true"` attribute. Users usually know that they can slide the circle to move through the video.
- Modified documentation including this two new attributes.
- Created new tests for the new functions, but surely can be improved.

feat(vgScrubBar): Enable seek using move events

---

src/core/vg-media/vg-media.ts

Automatically register vgMedia in case vgMedia.ngOnInit() has been executed but vgMedia is still not registered. This may happen specially when we create vgMedia directives dynamically.

fix(vgMedia): Automatically register vgMedia

---

src/streaming/vg-hls/vg-hls.ts

I cannot reproduce this error, but in our error logging service we get errors saying that element
doesn't have the `.pause()` method. Which it really should have but it somehow doesn't. I don't know how else to fix it, other then to add another check.
Fixes #473

fix(HLS): Adds check that target element really has pause method.

---

src/ima-ads/vg-ima-ads.ts

Don't throw 'ReferenceError: google is not defined' if ima3.js is not loaded.
If `imasdk.googleapis.com/js/sdkloader/ima3.js` script is loaded later then videogular a `google is not
defined` exception is thrown.
This doesnt happen often, so we're just if()-ing if google is undefined and then skipping banners. In any case, user doesn't see banners, this time he at least doesn't get the exception.
In reference to  #472.

fix(IMA ADS): Don't throw 'ReferenceError: google is not defined' 

---

core.ts

Add CustomEvent polyfill to fix Google IMA in IE10/11

fix(ima-ads): Fix Google IMA in IE10/11

---

src/buffering/vg-buffering.ts
src/core/vg-media/vg-media.spec.ts
src/core/vg-media/vg-media.ts

Improved buffering detection to detect only changes on src attribute or source child nodes. Also
fixed some corner cases that must remove the subscriptions to avoid multiple subscribes to the
buffer observable.
close #498

fix(core): Fix buffering detection

---

src/core/vg-media/vg-media.ts

BUG FIX: addTextTrack in VgMedia should return the new text track so it can be used.
Y - I've read the (contributing)[https://github.com/videogular/videogular2/blob/master/CONTRIBUTING.md] guidelines
Y - Code compiles correctly (run `npm start`)
N/A - Created tests (if necessary)
Y - All tests passing (run `npm test`)
N/A - Extended the README / documentation (if necessary)

fix(VgMedia) return new track from addTextTrack

---

src/core/vg-media/vg-media.ts

Quick fix to check when a `source` child list has been emptied

fix(core): Check when source childList is emptied

---

.travis.yml
karma.conf.js
package.json

Updated karma-chrome-launcher plugin, Karma config and Travis config to use Headless Chrome to run all tests.
Advantages:
- Tests should run faster in Headless Chrome
- Run tests in Travis in Chrome stable version, instead of [outdated Chromium stuck on version 37](https://github.com/travis-ci/travis-ci/issues/3475)
- Get rid of 'black magic' in Travis configuration and less clutter in Karma configuration file
Checked:
- All tests passing (run `npm test`) :)

Use Headless Chrome for tests

---

src/core/vg-media/vg-media.ts

VG-Media can hold onto subscription references when moving from page to page while a video is
playing.  Various subscriptions are set to unsubscribe on pause, but if the component is destroyed
while playing (with no pause event fired) a reference of Videogular gets held onto.  This change
adds an unsubscribe to any subscriptions that can be created (while checking for existence prior to
attempting an unsubscription).  The bufferDetected Subject also runs a complete to ensure
unsubcription of any subscribers, and then unsubcribes itself.  The unsubscription of itself might
be unnecessary, but as a Subject is both an Observable and an Observer this seemed to be the safest
approach.
565
Please explain the changes you made here. Commit your changes with `npm run commit` instead of `git …

fix(vg-media): Fix memory leaks when destroying playing video

---

src/core/vg-media/vg-media.ts

Avoid buffer detected emits when vg-media has been destroyed.

fix(core): Avoid buffer detected emits when vg-media has been destroyed.

---

src/controls/vg-play-pause/vg-play-pause.ts
src/controls/vg-volume/vg-volume.ts

fix(controls): Set ARIA orientation in VgVolume, Set play/pause button ARIA label depends on current state.
Here are some ARIA fixes. 
Changed play/pause button ARIA label depends on current state. It already has role='button' so screenreaders read this like 'play pause button button'.  
Added ARIA orientation state to volume slider, to let screenreader know that it's a "Left/right" slider.

fix(controls): Set ARIA orientation in VgVolume, Set play/pause button ARIA label depends on current state.

---

src/core/vg-media/vg-media.ts

`playPromise` attempts that are rejected drop into the catch block and were not clearing the
`playPromise` reference causing all subsequent attempts to play the media to fail.  The initial
if-statement checks for the existence of a `playPromise` and returns out if it currently exists.  This
meant that autoplay videos rejected by Safari or Chrome could not be played, even by clicking the
play button.  This change nulls out of the `playPromise` reference with both successful and
unsuccessful play attempts allowing future calls to play() (for example, during a click event of the
play button) the possibility to succeed.
This pull request resolves the issue discussed in #724 
```javascript
play() {
// short-circuit if already playing
if (this.playPromise || (this.state !== VgStates.VG_PAUSED …
```

fix(vgMedia): playPromise failures now remove the playPromise

---

src/core/services/vg-api.spec.ts
src/core/services/vg-api.ts

Within `vgAPI` `getMasterMedia` and `isMasterDefined` both were checking for `vgMedia` (an `IMediaElement`) being equal to
the boolean value `true` rather than the boolean value `vgMaster`.  This means that implementations that
include a `[vgMaster]="true"` definition always fail the test which makes `getMasterMedia` return
`getDefaultMedia`, equal to the first media object in the media collection.  This means that api
reports values in $$getAllProperties incorrectly.
This same error also existed in the vg-api unit tests, which allowed the test to erroneously pass.
This pull request resolves issue #729

fix(vgAPI): Fix syntax error in getMasterMedia and isMasterDefined

---

docs/modules/buffering/vg-buffering/README.md
docs/modules/controls/vg-controls/README.md
docs/modules/controls/vg-mute/README.md
docs/modules/controls/vg-play-pause/README.md
docs/modules/controls/vg-playback/README.md
docs/modules/controls/vg-scrub-bar/README.md
docs/modules/controls/vg-scrub-bar/vg-scrub-bar-buffering-time/README.md
docs/modules/controls/vg-scrub-bar/vg-scrub-bar-cue-points/README.md
docs/modules/controls/vg-scrub-bar/vg-scrub-bar-current-time/README.md
docs/modules/controls/vg-time-display/README.md
docs/modules/controls/vg-track-selector/README.md
docs/modules/controls/vg-volume/README.md
docs/modules/overlay-play/vg-overlay-play/README.md

vgFor is expecting an id string, not an object. Although, it would be
cool if [vgFor]="myMedia" also worked.
Please explain the changes you made here. Commit your changes with `npm run commit` instead of `git commit`.
Specify if it's a fix, feature or breaking change to update the version on NPM.
Thank you!
- Created tests (if necessary)
- All tests passing (run `npm test`)
- Extended the README / documentation (if necessary)

Fix vgFor references in docs

---

package.json
src/core/services/vg-fullscreen-api.spec.ts

Update method names of some tests in /vg-api.spec.ts to allow compatibility with last versions of chrome in tests.
Update version of husky.
- Created tests (if necessary)
- All tests passing (run `npm test`)
- Extended the README / documentation (if necessary)

test(chrome) Fix chrome tests for last versions

---

src/streaming/vg-hls/vg-hls.ts

vg-media currently sets the isLive property by determining if total time is bound to infinity.  This
allows that option, while also tracking manifest loaded events out of hls.js that report whether a
manifest is live or not.  This should account for both standard live streams, and dvr style live events that reach an ending while someone is watching (which should change isLive to false when the X-EndList appears in the polling manifest).
This commit also deletes the hls object in an attempt to resolve the spinning wheel issue reported in issue #726.  I could not replicate the issue reliably so I don't know if this will make any substantive difference, but deleting the object is done with both the clappr and videojs hls.js implementations, so I figured why not.
#740 #741

fix(vgHLS): Trigger isLive in vg-media for live HLS manifest

---

.travis.yml
src/core/vg-cue-points/vg-cue-points.ts

Please explain the changes you made here. Commit your changes with `npm run commit` instead of `git commit`.
Fix to ensure that the `this.ref.nativeElement.track` object exists before attempting to access it's cues.

Fix attempted cues access on undefined in DoCheck

---

src/core/vg-cue-points/vg-cue-points.ts

Esnure that track exists before attempting to access the track.cues
fix my commit message for my pull request to ensure semantic release releases a new version.
Fix
Thank you!

fix(cues) Ensure that track exists

---

package.json
src/controls/vg-fullscreen/vg-fullscreen.ts
src/core/services/vg-api.spec.ts

AudioTrackAPI typedefs were improved on TS < 3.5, Proto pollution vulnerabilities fix for dependencies, typo fix on vg-fullscreen, fixed failing test with typecasting
Closes #893

fix(package): TS version bump for AudioAPI type defs on compile
